version: '3.4'

services:
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile
    ports: 
      - 5001:5001
      - 5000:5000

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
